CREATE TABLE DONARS(DONAR_ID INT PRIMARY KEY NOT NULL identity,
FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),
EMAIL VARCHAR(150),
CONTACT VARCHAR(50),
GENDER VARCHAR(10) foreign key REFERENCES DROPDOWN(GENDER),
BLOODGRP VARCHAR(50),
ADDRESS VARCHAR(250),
AGE INT

);

select * from DONARS

INSERT INTO DONARS VALUES('RAVITEJA','kOLLURI','RAVITEJA@GMAIL.COM','9908009196','MALE','B+','KHAMMAM','22')
 INSERT INTO DONARS VALUES('MANASA','CHEKATI','CH.MANASA@GMAIL.COM','9876543906','FEMALE','0+','HYDERABAD','25')
 INSERT INTO DONARS VALUES('PRASAD','ALLA','PRASAD03@GMAIL.COM','9502817031','MALE','A-','BANGLORE','32')
 INSERT INTO DONARS VALUES('RAGHU','NAGALLA','RAGHU.N@GMAIL.COM','8976543210','MALE','0-','HYDERABAD','27')




  CREATE TABLE USERS(USER_ID INT PRIMARY KEY NOT NULL identity ,
EMAIL VARCHAR(150),
FULLNAME VARCHAR(50),
CONTACT VARCHAR(50),
ADDRESS VARCHAR(250),
BLOODGRP VARCHAR(5)
);

select * from USERS

INSERT INTO USERS VALUES('Sonika123@gmail.com','AallaSonika','9876543210','Hyderabad','A+')
INSERT INTO USERS VALUES('Vasavi@gmail.com','VasaviT','8907654321','Chennai','B+')
INSERT INTO USERS VALUES('Veda06@gmail.com','VedaReddy','7654321098','Banglore','A-')


CREATE TABLE LOGIN(U_Id int NOT NULL,
	Name nvarchar(50) NULL,
	Password nvarchar(50) NULL
)
INSERT INTO LOGIN VALUES(1,'Admin','Password')

Select * from LOGIN

CREATE TABLE Dropdown(
Gender Varchar(10) PRIMARY KEY NOT NULL
);
INSERT INTO Dropdown VALUES('Female')
INSERT INTO Dropdown VALUES('Male')
INSERT INTO Dropdown  VALUES('Others')

select * from Dropdown

Select GENDER From DROPDOWN