GO
CREATE PROCEDURE UpdateDonars(
@DONAR_ID  int,
@FIRST_NAME  nvarchar(50),
@LAST_NAME  nvarchar(50),
@EMAIL  nvarchar(150),
@CONTACT  nvarchar(50),
@GENDER nvarchar(50),
@BLOODGRP nvarchar(2),
@ADDRESS  nvarchar(250),
@AGE  int)

AS
IF @DONAR_ID in(select DONAR_ID from DONARS)
BEGIN
  	update DONARS set FIRST_NAME=@FIRST_NAME,LAST_NAME=@LAST_NAME,EMAIL=@EMAIL,CONTACT=@CONTACT,GENDER=@GENDER,BLOODGRP=@BLOODGRP,ADDRESS=@ADDRESS,AGE=@AGE where DONAR_ID=@DONAR_ID
	

RETURN 1
END
ELSE
BEGIN
RETURN 0
END

select * from donars